apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    dev.okteto.com/generate-host: "true"
  name: "{{ include "chart.fullname" . }}"
spec:
  rules:
  - http:
      paths:
      - path: /ping
        pathType: "Prefix"
        backend:
          service:
            name: "{{ include "chart.fullname" . }}"
            port: 
              name: http
