apiVersion: v1
kind: Service
metadata:
  name: "{{ include "chart.fullname" . }}"
spec:
  type: ClusterIP
  selector:
    app: "{{ include "chart.fullname" . }}"
  ports:
  - name: http
    port: 8080
    targetPort: http
