apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ include "chart.fullname" . }}"
  annotations:
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
